### ISSUE TITLE
Preserve this-command to make consult-company works with vertico-multiform-mode

### ISSUE THREAD

**Issue by BooAA** [mohkale/consult-company#7]
Context: https://github.com/minad/vertico/issues/350

I tried to tune `vertico-multiform-mode` to make `consult-company` display content in normal buffer, but failed. According to @minad, this is because `consult-company` didn't preserve `this-command` before calling `completing-read`, is it ok for `consult-company` to fix this? Thanks.

**Comment by mohkale** [comment]
@BooAA 

This should be fixed now. Please reopen this ticket if you have any issues.
