### ISSUE TITLE
regular company popup is opened after I press C-g

### ISSUE THREAD

**Issue by yherve** [mohkale/consult-company#8]
Hi. I'm just starting to configure consult-company. 

- When I call consult-company it displays the completion list as expected.
- If I choose an entry it completes it fine.

but If I press C-g to cancel the completion it opens the company popup, which I have to close by pressing C-g again

Is there a way to prevent this behaviour ?

**Comment by mohkale** [comment]
This is a consequence of how this package works. It extracts completion candidates from company and the only way to do so is to show the company ui. I suppose we could detect when we are the ones to show the UI and then close it afterwards. I tried doing this with an unwind-protect around company-finish. Please try the version in #9. If it works for you then we can merge it.

**Comment by yherve** [comment]
yes your patch solved the problem. Thanks (and thanks for this great package)
